### ISSUE TITLE
Todo List

### ISSUE THREAD

**Issue by Kiritsu** [Kiritsu/FoxBot#1]
# List of the modules to implement

- [ ] Reminder with db tracking
- [ ] League of Legends module + stats track
- [ ] Osu! module + stats track
- [ ] Mute/Unmute commands in moderation module with db tracking
- [ ] Image manipulation module
- [ ] Experience module
- [ ] Gold module (maybe linked with rpg below)
- [ ] Simple RPG Game module/service/database
